spring.application.name=order-risk-pipeline
spring.datasource.url=jdbc:postgresql://localhost:5432/order_risk_pipeline_db
spring.datasource.username=adminuser
spring.datasource.password=unixbox
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer